# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 11:26
from __future__ import unicode_literals

import apiservice.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kitchen', 'Кухня'), ('client', 'Клиент')], max_length=128, verbose_name='Тип чека')),
                ('order', django.contrib.postgres.fields.jsonb.JSONField(default=dict, validators=[apiservice.validators.JSONSchemaValidator(limit_value={'$schema': 'http://json-schema.org/draft-07/schema#', 'properties': {'address': {'$id': '#/properties/address', 'pattern': '^(.*)$', 'type': 'string'}, 'client': {'$id': '#/properties/client', 'properties': {'name': {'$id': '#/properties/client/properties/name', 'pattern': '^(.*)$', 'type': 'string'}, 'phone': {'$id': '#/properties/client/properties/phone', 'type': 'integer'}}, 'required': ['name', 'phone'], 'type': 'object'}, 'id': {'$id': '#/properties/id', 'type': 'integer'}, 'items': {'$id': '#/properties/items', 'items': {'$id': '#/properties/items/items', 'properties': {'name': {'$id': '#/properties/items/items/properties/name', 'pattern': '^(.*)$', 'type': 'string'}, 'quantity': {'$id': '#/properties/items/items/properties/quantity', 'type': 'integer'}, 'unit_price': {'$id': '#/properties/items/items/properties/unit_price', 'type': 'integer'}}, 'required': ['name', 'quantity', 'unit_price'], 'type': 'object'}, 'type': 'array'}, 'point_id': {'$id': '#/properties/point_id', 'type': 'integer'}, 'price': {'$id': '#/properties/price', 'type': 'integer'}}, 'required': ['id', 'price', 'items', 'address', 'client', 'point_id'], 'type': 'object'})])),
                ('order_id', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('rendered', 'Конвертирован'), ('printed', 'Распечатан')], default='new', max_length=128, verbose_name='Статус чека')),
                ('pdf_file', models.FileField(default=None, upload_to='pdf')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('api_key', models.CharField(max_length=256, unique=True)),
                ('check_type', models.CharField(choices=[('kitchen', 'Кухня'), ('client', 'Клиент')], default='kitchen', max_length=128, verbose_name='Тип чека')),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='printer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiservice.Printer', verbose_name='Принтер'),
        ),
    ]
